name: Format CI

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install clang-format
      run: nix-env -iA nixpkgs.clang-tools 
    
    - name: Apply clang-format
      run: /usr/bin/find . \( -iname *.c -o -iname *.h \) -exec clang-format -i {} \;

    - name: Check for changes
      run: |
        git diff
        if ! git diff --exit-code; then
          echo "Code format differences found."
          exit 1
        fi
