name: GNU/Make CI

on:
  push:
      branches: [ main prelib ]
  pull_request:
      branches: [ main prelib ]
    
jobs:
  make-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]


    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch libraries
      run: |
        ./.github/scripts/get-helpers.sh
      working-directory: ${{ github.workspace }}


    - name: Create necessary folders
      run: |
        mkdir -p build/helpers

    - name: Initialize and Build project
      run: make
    
    - name: Cleanup dirty project
      run: make clean