name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # Setup Nix
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        install_options: --daemon --extra-experimental-features 'nix-command flakes'

    # Build the project using Nix
    - name: Build
      run: nix build
      
    # Run the project (replace './result/bin/myapp' with your binary path)
    - name: Run
      run: ./result/bin/nya