name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Fetch libraries
      run: ./.github/scripts/get-helpers.sh
      working-directory: ${{ github.workspace }}
  
    - name: Add lib files to track
      run: git add helpers/*
      working-directory: ${{ github.workspace }}

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}


    - name: Build
      run: nix build

    - name: Check flake
      run: nix flake check
      
    - name: Run
      run: ./result/bin/nya

    - name: Remote run
      run: |
        nix run github:NyanSystems/nya